#!/bin/bash

underline=`tput smul`
noUnderline=`tput rmul`
bold=`tput bold`
normal=`tput sgr0`

scriptName=$(basename $0)
scriptDir=$(dirname $0)

error() {
	# echo error message if one has been provided
	if [ $# -gt 0 ]; then
		echo "$0: $1"
	fi

	echo "Incorrect usage of $scriptName"
	echo "Please use -h or --help option for further information"
}

help() {
	echo "$scriptName provides simplified systemd httpd.service commands"
	echo
	echo "${bold}Usage${normal}: ${scriptName} [option] command"
	echo "${bold}command${normal} is the name of the systemctl command you want to use."
	echo
	echo "Options:"
	echo " - ${bold}h${normal}        Print this help"
    echo
    echo "Commands:"
    echo " - ${bold}status${normal}         Alias for 'systemctl status" \
            "syncthing.service'"
    echo " - ${bold}start${normal}         Alias for 'systemctl start" \
            "syncthing.service'"
    echo " - ${bold}stop${normal}         Alias for 'systemctl stop" \
            "syncthing.service'"
}

httpd() {
    case "$1" in
        "status")
            systemctl status httpd.service;;
        "start")
            systemctl start httpd.service;;
        "stop")
            systemctl stop httpd.service;;
    esac
}

while getopts "h" option; do
	case $option in
		h)
			help
			exit;;
		\?)
			error
			exit;;
	esac
done

# determine if an argument has been passed
if [ $# -gt 0 ]; then
	httpd $1
else
	error "an argument is required"
fi
